name: "Mirror"

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 20 * * *'

jobs:
  run:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Manually mirror
      run: |
        mirror() {
          git clone "https://github.com/$1/$2"
          cd "$2"
          git remote add gitee "https://jaywcjlove:${{ secrets.GITEE_TOKEN }}@gitee.com/uiw/$2.git"
          git remote set-head origin -d
          git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
          cd ..
        }
        mirror uiwjs react-md-editor
        mirror uiwjs react-baidu-map
        mirror uiwjs react-native-uiw
        mirror uiwjs react-codemirror
        mirror uiwjs react-shields
        mirror uiwjs react-github-corners
        mirror uiwjs react-markdown-editor
        mirror uiwjs react-code-preview
        mirror uiwjs reset-css
        mirror uiwjs react-markdown-preview
        mirror uiwjs logo
        mirror uiwjs icons
        mirror uiwjs province-city-china
        mirror uiwjs react-native-alipay
